# Generated by Django 5.0.6 on 2024-07-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('humidite', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RapportAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date_generation', models.DateField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('date_entree', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('date_vente', models.DateField()),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_plantation', models.DateField()),
                ('date_recolte', models.DateField()),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestCulture.agriculteur')),
            ],
        ),
        migrations.CreateModel(
            name='CalendrierPlantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestCulture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='MethodeGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestCulture.culture')),
            ],
        ),
    ]
