# Generated by Django 5.0.6 on 2024-07-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestCulture', '0002_alter_rapportanalyse_options_donneemeteo_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculteur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendrierplantation',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='methodegestion',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rapportanalyse',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
