# Generated by Django 5.0.6 on 2024-07-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestCulture', '0003_agriculteur_actif_calendrierplantation_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculteur',
            name='prenom',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
