# Generated by Django 5.0.6 on 2024-07-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestCulture', '0004_agriculteur_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriculteur',
            name='prenom',
        ),
    ]
